stamm_1:
                DW 0015H
                DB 01EH
                DW 0051H
                DD 0091E60F1H
                DW 00BDH
                DB 0A3H
                DW 00F7H
                DD 00B7405FAH
stamm_2:
                DW 0006H
                DB 0B4H
                DW 0022H
                DD 0F1EBF71EH
                DW 00B3H
                DB 080H
                DW 00DFH
                DD 03D021624H
stamm_3:
                DW 0032H
                DB 01EH
                DW 005EH
                DD 001B82595H
                DW 00C5H
                DB 033H
                DW 00E1H
                DD 0B104C9E9H
stamm_4:
                DW 003EH
                DB 0FAH
                DW 005AH
                DD 08B134C0BH
                DW 00CDH
                DB 080H
                DW 00F9H
                DD 059E0DF7FH
stamm_5:
                DW 0009H
                DB 02EH
                DW 0025H
                DD 0E809E525H
                DW 0037H
                DB 0E8H
                DW 0063H
                DD 04B02F8A4H
stamm_6:
                DW 0009H
                DB 050H
                DW 0025H
                DD 000845225H
                DW 0043H
                DB 080H
                DW 006FH
                DD 003449A4EH
stamm_7:
                DW 001AH
                DB 050H
                DW 0046H
                DD 0C033CBADH
                DW 0085H
                DB 0A1H
                DW 00A1H
                DD 0A306FD1BH
stamm_8:
                DW 0036H
                DB 0B8H
                DW 0052H
                DD 050E0C65BH
                DW 00B2H
                DB 09CH
                DW 00DEH
                DD 08EC9E34EH
stamm_9:
                DW 0007H
                DB 08EH
                DW 0023H
                DD 002A20883H
                DW 00B3H
                DB 091H
                DW 00DFH
                DD 00315FE59H

stamms_num      equ     9
stamms_max_ip   equ     254
