

THIS MESSAGE IS TO ALL AND VALID AS OF JULY 1, 1994:

As noted in this issue, MY TELEPHONE LINE IS TEMPORARILY OUT OF SERVICE.  Mail
left for me will be responded to upon my return.  SCAM! will, however, continue
to be transmitted via emergency means until a new line is secured, and I will
hopefully be re-infecting the scene again soon.  I MISS YOU GUYS!!  And what's
worse, MY LINE WENT OUT BEFORE COREL DRAW 5 GOT RELEASED!!! hahahah...

Have a great fucking summer, everybody.  See you soon.

ÄÄÄ The Producer
 
