@echo off
cls
echo oKay y00 g0t dAh 0-Day.
echo HaVe y00 uN-ZiPpEd thiS aRcHiVE iNt0 y00r d00m diReCtoRy?
echo iF tHe aNsWeR iZ n0 dEn pReSS CTRL-C aNd d00 iT..
pause
cls
echo 0Kay lEtZ g00 pH0R iT!!
echo oH bTw iF y00 c0ULdn'T c0mPLeTe Episode 1 LeVeL 1 SkiLL d0nT hUrT mE
echo eYe sUggEsT y00 pReSS CTRL-C aNd LiVe iN pHeAr!!!
pause
cls
doom -episode 1 -file bow.wad -skill 1
cls
echo s0 diD y00 c0MpLeTe iT? eZi hUh? hEh...
echo LaTeRz
echo -=[BooYaa]=-
