Úִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ¿
³ QiC Net Application                                     Information ³
ְִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ ת..ת ת..ת ִִÙ
 
 QiC is basicly a H/P Warez net, I am limiting it to 3-6 BBS's per 
 area code, all depending on how large the area code is.

 To Get your BBS in the net just fill out the app and send it to:
              
                 Suburban Wasteland (QiC WHQ)
                       (219) 365-1096

  You should either apply for access on Suburban Wasteland and attach the
  app to your letter to Cyborg, or leave Matrix feedback with your app
  attached to it.




Úִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ¿
³ QiC Net Application                            Personal Information ³
ְִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ ת..ת ת..ת ִִÙ
  Full Name [תתתתתתתתתתתתתתתתתתתתתתתת]  Voice # [תתת]תתת-תתתת
  Handle [תתתתתתתתתתתתתתתתתתתתתתתתתתת]  Birthdate/Age [תת/תת/תת] [תתת]
  Address [תתתתתתתתתתתתתתתתתתתתתתתתתת]  City, State [תתתתתתתתתתת,תת]
                                        Zip Code [תתתתת-תתתת]

 [None of the above information will be released to anyone it is
 for my use only]

Úִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ¿
³ QiC Net Application                        Board/Mailer Information ³
ְִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ ת..ת ת..ת ִִÙ
  Board Name [תתתתתתתתתתתתתתתתתתתתתתת]  BBS  # [תתת]תתת-תתתת
  BBS Software [תתתתתתתתתתתתתתתתתתתתת]  Version [תתתתתתתתתתתתתת]
  Months in Operation [תתתתתתתתתתתתתת]  Hours [תתתתתתתתתתתתתתתת]
  Mailer Software [תתתתתתתתתתתתתתתתתת]  Version [תתתתתתתתתתתתתת]
  Tosser Software [תתתתתתתתתתתתתתתתתת]  Version [תתתתתתתתתתתתתת]
  Modem Prot/Comm [תתתתתתתתתתתתתתתתתת[  Max Baud [תתתתתתתתתתתתת]
  Are you experienced with setting up nets? [תתת]
  Other Nets .תAddressת.         .תNetnameת.
           [תתתתתתתתתתתתת] - [תתתתתתתתתתתתתתתתתת]
           [תתתתתתתתתתתתת]   [תתתתתתתתתתתתתתתתתת]
           [תתתתתתתתתתתתת]   [תתתתתתתתתתתתתתתתתת]
           [תתתתתתתתתתתתת]   [תתתתתתתתתתתתתתתתתת]
           [תתתתתתתתתתתתת]   [תתתתתתתתתתתתתתתתתת]
           [תתתתתתתתתתתתת]   [תתתתתתתתתתתתתתתתתת]

Úִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ¿
³ QiC Net Application                               Other Information ³
ְִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִִ ת..ת ת..ת ִִÙ
  How often would you be willing to call your local Hub? [תתתתתתתתתתתתתתתתת]
  Would you be willing to be a Hub if you had to? [תתת]
  Is there any other board/misc/etc information you would like to tell
  me.

  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
  [תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת]
